### ISSUE TITLE
Various sentences by different speakers interaligned

### ISSUE THREAD

**Issue by prakharg24** [gcunhase/AMICorpusXML#4]
Hi,

From what I understand, the final transcripts that you create for every individual meeting contains all the sentences spoken by every speaker individually. But there are no alignments present between them which means it cannot be turned into an actual dialogue/conversation.

For example I want the following conversation,

Speaker A : Hi
Speaker B : Hello. What are you doing here?
Speaker A : The supervisor called me in. He wanted to have a word.
Speaker B : Well good luck. He is in a mood today.

However, the final transcripts provided in your repo is of the following format.
Speaker A : Hi. The supervisor called me in. He wanted to have a word.
Speaker B : Hello. What are you doing here? Well good luck. He is in a mood today.

Can you help me creating the dialogue format that I require? Or guide me what files in AMI corpus can I use to obtain the same?

Thank You

**Comment by gcunhase** [comment]
Hi,

Your understanding of how this repository works is correct. As of now, I haven't done the dialog style conversation that you need. The reason being that, unfortunately, since it's a meeting setting, people often talk over each other and that makes it really hard to create such dataset.

It is on my todo list but I currently don't have time to complete that task. It would be greatly appreciated if you forked this repository and once you've completed that, I can merge your code with mine.

Sorry I couldn't be more helpful right now.

**Comment by Utkichaps** [comment]
Hey!

You can try [this](https://github.com/Utkichaps/AMICorpus-Meeting-Transcript-Extraction) out for converting the meeting transcripts into a speaker by speaker representation

**Comment by gcunhase** [comment]
Thank you @Utkichaps! Hope that helps @prakharg24.
